[package]
name = "client-world"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
publication-test-support = []

[dependencies]
actor-animation = { path = "../actor-animation" }
assets = { path = "../assets" }
crossbeam-channel = "0.5"
bytes.workspace = true
hashbrown = "0.16"
meshing = { path = "../meshing" }
protocol = { path = "../protocol" }
render-data = { path = "../render-data" }
rayon.workspace = true
sha2 = "0.10"
thiserror.workspace = true
world = { path = "../world" }
